CREATE TABLE IF NOT EXISTS `user` (
  `id` VARCHAR(64) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `role` VARCHAR(64) DEFAULT 'user',
  `phone` VARCHAR(128) DEFAULT NULL,
  `isEnabled` BOOLEAN NOT NULL DEFAULT TRUE,
  `dateCreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateEdited` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE `email` (`email`),
  UNIQUE `phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
