CREATE TABLE IF NOT EXISTS `dummy` (
  `id` VARCHAR(64) NOT NULL,
  `isEnabled` BOOLEAN NOT NULL DEFAULT TRUE,
  `dateCreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateEdited` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `dummy`
ADD COLUMN IF NOT EXISTS
`name` VARCHAR(256) DEFAULT NULL
AFTER `id`;
