CREATE TABLE IF NOT EXISTS `dummy` (
  `id` VARCHAR(64) NOT NULL,
  `dateCreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateEdited` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `isEnabled` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
